name: Build and Release App

on:
  push:
    tags:
      - 'v*'  # 仅在以 "v" 开头的 tag 被推送时触发
  workflow_dispatch:  # 添加手动触发

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/blindbox_tool_android.apk

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/blindbox_tool_android.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Create Windows installer
        run: |
          Compress-Archive -Path "build/windows/x64/runner/Release/*" -DestinationPath "blindbox_tool_windows.zip"
        shell: powershell

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: blindbox_tool_windows.zip

  build-macos:
    runs-on: macos-15  # 使用固定版本避免迁移警告
    strategy:
      matrix:
        include:
          - arch: x64
            excluded_archs: arm64
          - arch: arm64
            excluded_archs: x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Configure Architecture (${{ matrix.arch }})
        run: |
          # 修改 Podfile 以排除特定架构
          if [ -f "macos/Podfile" ]; then
            echo "post_install do |installer|" >> macos/Podfile
            echo "  installer.pods_project.targets.each do |target|" >> macos/Podfile
            echo "    target.build_configurations.each do |config|" >> macos/Podfile
            echo "      config.build_settings['EXCLUDED_ARCHS[sdk=macos*]'] = '${{ matrix.excluded_archs }}'" >> macos/Podfile
            echo "    end" >> macos/Podfile
            echo "  end" >> macos/Podfile
            echo "end" >> macos/Podfile
          fi

      - name: Build macOS App (${{ matrix.arch }})
        run: flutter build macos --release

      - name: Create DMG
        run: |
          brew install create-dmg
          
          APP_NAME="Blindbox Tool"
          DMG_NAME="blindbox_tool_macos_${{ matrix.arch }}.dmg"
          
          # 获取实际的 app 名称
          APP_PATH=$(find build/macos/Build/Products/Release -name "*.app" -type d | head -n 1)
          APP_BASENAME=$(basename "$APP_PATH")
          
          create-dmg \
            --volname "$APP_NAME" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "$APP_BASENAME" 200 190 \
            --hide-extension "$APP_BASENAME" \
            --app-drop-link 600 185 \
            "$DMG_NAME" \
            "build/macos/Build/Products/Release/" || true

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-${{ matrix.arch }}
          path: blindbox_tool_macos_${{ matrix.arch }}.dmg

  release:
    needs: [build-android, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files
        run: find . -type f -name "*" | head -20

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android-apk/blindbox_tool_android.apk
            windows-exe/blindbox_tool_windows.zip
            macos-dmg-x64/blindbox_tool_macos_x64.dmg
            macos-dmg-arm64/blindbox_tool_macos_arm64.dmg
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}