# .github/workflows/release.yml
name: Release Electron App

on:
  workflow_run:
    workflows: ["Build Electron App"]  # 触发这个工作流的名称
    types:
      - completed  # 仅当工作流完成时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # 使用当前的 tag 作为发布的 tag
          body: 'Release description'
          files: |
            dist/mystery-box-result**  # 上传 dist 目录下的所有文件
          draft: false  # 设置为 false 以发布正式版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 确保使用有效的 token
